//! WASM target emitter — reuses Rust IR lowering with wasm32 crate layout.

use emit_rust::emit;
use ir::Program;

pub struct WasmOutput {
    pub cargo_toml: String,
    pub lib_rs: String,
}

pub fn emit_wasm(program: &Program) -> WasmOutput {
    let rust = emit(program);
    let lib_rs = rust
        .main_rs
        .replace("fn main()", "pub fn qp_main()")
        .replace(
            "// Generated by Quantum Point",
            "// Generated by Quantum Point (wasm)",
        );

    let cargo_toml = r#"[package]
name = "qp_wasm"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[profile.release]
opt-level = "s"
"#
    .to_string();

    WasmOutput { cargo_toml, lib_rs }
}

pub fn write_wasm(out_dir: &std::path::Path, program: &Program) -> std::io::Result<()> {
    let out = emit_wasm(program);
    let src = out_dir.join("src");
    std::fs::create_dir_all(&src)?;
    std::fs::write(out_dir.join("Cargo.toml"), out.cargo_toml)?;
    std::fs::write(src.join("lib.rs"), out.lib_rs)?;
    Ok(())
}
