//! View domain emitter — UI tree (`.qpview` spec) + optional Rust stub.

use graph_model::{
    data_get_str, Project, NODE_UI_BUTTON, NODE_UI_EVENT, NODE_UI_INPUT, NODE_UI_LABEL,
    NODE_UI_PAGE,
};
use qp_domain::Domain;
use std::fmt::Write;

#[derive(Debug, Clone)]
pub struct ViewOutput {
    pub spec: String,
    pub rust_stub: String,
}

#[derive(Debug, Clone)]
pub struct ViewSpecItem {
    pub id: String,
    pub kind: String,
    pub title: String,
    pub attrs: Vec<String>,
}

/// Parse `.qpview` lines produced by `emit_view`.
pub fn parse_view_spec(spec: &str) -> Vec<ViewSpecItem> {
    let mut items = Vec::new();
    let mut current: Option<ViewSpecItem> = None;
    for line in spec.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with("- ") {
            if let Some(c) = current.take() {
                items.push(c);
            }
            let rest = line.trim_start_matches("- ");
            let (id, kind, title) = parse_spec_header(rest);
            current = Some(ViewSpecItem {
                id,
                kind,
                title,
                attrs: Vec::new(),
            });
        } else if let Some(c) = current.as_mut() {
            c.attrs.push(line.to_string());
        }
    }
    if let Some(c) = current {
        items.push(c);
    }
    items
}

fn parse_spec_header(rest: &str) -> (String, String, String) {
    if let Some(lb) = rest.find('[') {
        let id = rest[..lb].trim().to_string();
        let after = &rest[lb + 1..];
        if let Some(rb) = after.find(']') {
            let kind = after[..rb].trim().to_string();
            let title = after[rb + 1..]
                .trim()
                .trim_start_matches('-')
                .trim()
                .to_string();
            return (id, kind, title);
        }
    }
    (rest.trim().to_string(), String::new(), String::new())
}

pub fn emit_view(project: &Project) -> Result<ViewOutput, ViewEmitError> {
    if Domain::from_layer(project.layer) != Domain::View {
        return Err(ViewEmitError::WrongLayer(project.layer));
    }
    let mut spec = String::from("# Quantum Point View spec\n");
    let mut rust = String::from("// View stub — generated by Quantum Point\n\n");
    writeln!(rust, "pub struct {}Ui {{", sanitize_mod(&project.name)).unwrap();
    writeln!(rust, "    pub root: &'static str,").unwrap();

    for node in &project.nodes {
        if node.kind == graph_model::NODE_START {
            continue;
        }
        let title = data_get_str(&node.data, "title")
            .or_else(|| data_get_str(&node.data, "text"))
            .or_else(|| data_get_str(&node.data, "placeholder"))
            .unwrap_or_else(|| node.id.clone());
        writeln!(spec, "- {} [{}] {}", node.id, node.kind, title).unwrap();
        writeln!(rust, "    pub {}: ViewNode,", sanitize_field(&node.id)).unwrap();
        match node.kind.as_str() {
            NODE_UI_PAGE => {
                writeln!(spec, "  layout: page").unwrap();
            }
            NODE_UI_BUTTON => {
                writeln!(spec, "  widget: button").unwrap();
            }
            NODE_UI_LABEL => {
                writeln!(spec, "  widget: label").unwrap();
            }
            NODE_UI_INPUT => {
                writeln!(spec, "  widget: input").unwrap();
            }
            NODE_UI_EVENT => {
                let ev = data_get_str(&node.data, "event").unwrap_or_default();
                writeln!(spec, "  event: {ev}").unwrap();
            }
            _ => {}
        }
    }
    writeln!(rust, "}}\n").unwrap();
    writeln!(
        rust,
        "pub struct ViewNode {{ pub id: &'static str, pub kind: &'static str }}"
    )
    .unwrap();

    Ok(ViewOutput {
        spec,
        rust_stub: rust,
    })
}

#[derive(Debug, thiserror::Error)]
pub enum ViewEmitError {
    #[error("not a View layer graph")]
    WrongLayer(graph_model::GraphLayer),
}

fn sanitize_mod(name: &str) -> String {
    let mut out = String::new();
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
        }
    }
    if out.is_empty() {
        "App".to_string()
    } else {
        out
    }
}

fn sanitize_field(id: &str) -> String {
    let mut out = String::new();
    for (i, c) in id.chars().enumerate() {
        if i == 0 && c.is_ascii_digit() {
            out.push('n');
        }
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        "node".to_string()
    } else {
        out
    }
}
