use ir::{emit_value_expr, sanitize_ident, Action, Program, ValueExpr};
use std::fmt::Write;

pub struct RustOutput {
    pub cargo_toml: String,
    pub main_rs: String,
}

pub fn emit(program: &Program) -> RustOutput {
    let mut main_rs = String::new();
    writeln!(
        &mut main_rs,
        "// Generated by Quantum Point — do not edit by hand.\n"
    )
    .unwrap();
    writeln!(
        &mut main_rs,
        "fn qp_mock_rows(table: &str) -> Vec<(&'static str, &'static str)> {{"
    )
    .unwrap();
    writeln!(
        &mut main_rs,
        "    match table {{"
    )
    .unwrap();
    writeln!(
        &mut main_rs,
        "        \"users\" => vec![(\"id\", \"1\"), (\"name\", \"Ada\")],"
    )
    .unwrap();
    writeln!(
        &mut main_rs,
        "        \"orders\" => vec![(\"id\", \"100\"), (\"total\", \"42\")],"
    )
    .unwrap();
    writeln!(
        &mut main_rs,
        "        _ => vec![(\"id\", \"0\"), (\"table\", table)],"
    )
    .unwrap();
    writeln!(&mut main_rs, "    }}").unwrap();
    writeln!(&mut main_rs, "}}\n").unwrap();

    if program.needs_async_runtime {
        writeln!(&mut main_rs, "#[tokio::main]").unwrap();
        writeln!(&mut main_rs, "async fn main() {{").unwrap();
    } else {
        writeln!(&mut main_rs, "fn main() {{").unwrap();
    }
    for action in &program.actions {
        emit_action(&mut main_rs, action, 1);
    }
    writeln!(&mut main_rs, "}}").unwrap();

    let mut cargo_toml = r#"[workspace]

[package]
name = "qp_app"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "qp_app"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
"#
    .to_string();

    if program.needs_async_runtime {
        cargo_toml.push_str(
            r#"
[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
"#,
        );
    }

    RustOutput {
        cargo_toml,
        main_rs,
    }
}

fn emit_action(out: &mut String, action: &Action, indent: usize) {
    let pad = "    ".repeat(indent);
    match action {
        Action::Print { message } => {
            writeln!(out, "{pad}println!(\"{}\");", escape_rust_str(message)).unwrap();
        }
        Action::DataStore { name, value } => {
            let ident = sanitize_ident(name);
            let rhs = infer_rhs(value);
            writeln!(out, "{pad}let {ident} = {rhs};").unwrap();
        }
        Action::DbRead { table, into_var } => {
            let ident = sanitize_ident(into_var);
            writeln!(
                out,
                "{pad}let {ident} = qp_mock_rows({:?}).into_iter().next().unwrap_or((\"id\", \"0\"));",
                table
            )
            .unwrap();
            writeln!(
                out,
                "{pad}println!(\"db.read {{}} -> {{:?}}\", {:?}, {ident});",
                table
            )
            .unwrap();
        }
        Action::Module { name, actions } => {
            writeln!(out, "{pad}{{ // module {name}").unwrap();
            for a in actions {
                emit_action(out, a, indent + 1);
            }
            writeln!(out, "{pad}}}").unwrap();
        }
        Action::Branch {
            condition,
            then_body,
            else_body,
        } => {
            let cond = emit_value_expr(condition);
            writeln!(out, "{pad}if {cond} {{").unwrap();
            for a in then_body {
                emit_action(out, a, indent + 1);
            }
            if else_body.is_empty() {
                writeln!(out, "{pad}}}").unwrap();
            } else {
                writeln!(out, "{pad}}} else {{").unwrap();
                for a in else_body {
                    emit_action(out, a, indent + 1);
                }
                writeln!(out, "{pad}}}").unwrap();
            }
        }
        Action::While { condition, body } => {
            let cond = emit_value_expr(condition);
            writeln!(out, "{pad}while {cond} {{").unwrap();
            for a in body {
                emit_action(out, a, indent + 1);
            }
            writeln!(out, "{pad}}}").unwrap();
        }
        Action::For { var, from, to, body } => {
            let ident = sanitize_ident(var);
            writeln!(out, "{pad}for {ident} in {from}..={to} {{").unwrap();
            for a in body {
                emit_action(out, a, indent + 1);
            }
            writeln!(out, "{pad}}}").unwrap();
        }
        Action::ForEach {
            item_var,
            collection,
            body,
        } => {
            let item = sanitize_ident(item_var);
            writeln!(
                out,
                "{pad}for {item} in qp_mock_rows({:?}) {{",
                collection
            )
            .unwrap();
            for a in body {
                emit_action(out, a, indent + 1);
            }
            writeln!(out, "{pad}}}").unwrap();
        }
        Action::Return { value } => {
            if let Some(v) = value {
                writeln!(out, "{pad}return {};", infer_rhs(v)).unwrap();
            } else {
                writeln!(out, "{pad}return;").unwrap();
            }
        }
        Action::Switch {
            discriminant,
            arms,
            default_body,
        } => {
            let disc = emit_value_expr(discriminant);
            writeln!(out, "{pad}match &{disc} {{").unwrap();
            for arm in arms {
                let pat = switch_arm_pattern(&arm.label);
                writeln!(out, "{pad}    {pat} => {{").unwrap();
                for a in &arm.body {
                    emit_action(out, a, indent + 2);
                }
                writeln!(out, "{pad}    }}").unwrap();
            }
            writeln!(out, "{pad}    _ => {{").unwrap();
            for a in default_body {
                emit_action(out, a, indent + 2);
            }
            writeln!(out, "{pad}    }}").unwrap();
            writeln!(out, "{pad}}}").unwrap();
        }
        Action::Break => {
            writeln!(out, "{pad}break;").unwrap();
        }
        Action::Continue => {
            writeln!(out, "{pad}continue;").unwrap();
        }
        Action::Try {
            try_body,
            catch_body,
        } => {
            writeln!(out, "{pad}match (|| -> Result<(), String> {{").unwrap();
            for a in try_body {
                emit_action(out, a, indent + 1);
            }
            writeln!(out, "{pad}    Ok(())").unwrap();
            writeln!(out, "{pad}}})() {{").unwrap();
            writeln!(out, "{pad}    Ok(()) => {{}},").unwrap();
            writeln!(out, "{pad}    Err(_e) => {{").unwrap();
            for a in catch_body {
                emit_action(out, a, indent + 2);
            }
            writeln!(out, "{pad}    }}").unwrap();
            writeln!(out, "{pad}}}").unwrap();
        }
        Action::Expr { name, value } => {
            let ident = sanitize_ident(name);
            writeln!(out, "{pad}let {ident} = {};", emit_value_expr(value)).unwrap();
        }
        Action::Async { body } => {
            writeln!(out, "{pad}{{").unwrap();
            for a in body {
                emit_action(out, a, indent + 1);
            }
            writeln!(out, "{pad}}}").unwrap();
        }
    }
}

fn switch_arm_pattern(label: &str) -> String {
    if let Ok(n) = label.parse::<i64>() {
        format!("{n}")
    } else if label == "true" || label == "false" {
        label.to_string()
    } else {
        format!("{label:?}")
    }
}

fn infer_rhs(value: &ValueExpr) -> String {
    match value {
        ValueExpr::Bool(b) => b.to_string(),
        ValueExpr::I64(n) => n.to_string(),
        ValueExpr::F64(n) => format!("{n}"),
        ValueExpr::Str(s) => format!("{s:?}"),
        ValueExpr::Ident(name) => sanitize_ident(name),
        other => emit_value_expr(other),
    }
}

fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
