use ir::{emit_value_expr, sanitize_ident, Action, Program, ValueExpr};
use std::fmt::Write;

pub struct RustOutput {
    pub cargo_toml: String,
    pub main_rs: String,
}

pub fn emit(program: &Program) -> RustOutput {
    let mut main_rs = String::new();
    writeln!(
        &mut main_rs,
        "// Generated by Quantum Point — do not edit by hand.\n"
    )
    .unwrap();
    writeln!(&mut main_rs, "fn main() {{").unwrap();
    for action in &program.actions {
        emit_action(&mut main_rs, action, 1);
    }
    writeln!(&mut main_rs, "}}").unwrap();

    let cargo_toml = r#"[workspace]

[package]
name = "qp_app"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "qp_app"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
"#
    .to_string();

    RustOutput {
        cargo_toml,
        main_rs,
    }
}

fn emit_action(out: &mut String, action: &Action, indent: usize) {
    let pad = "    ".repeat(indent);
    match action {
        Action::Print { message } => {
            writeln!(out, "{pad}println!(\"{}\");", escape_rust_str(message)).unwrap();
        }
        Action::DataStore { name, value } => {
            let ident = sanitize_ident(name);
            let rhs = infer_rhs(value);
            writeln!(out, "{pad}let {ident} = {rhs};").unwrap();
        }
        Action::DbRead { table, into_var } => {
            let ident = sanitize_ident(into_var);
            writeln!(
                out,
                "{pad}// db.read mock: {table}\n{pad}let {ident} = (\"id\", \"1\");"
            )
            .unwrap();
            writeln!(
                out,
                "{pad}println!(\"db.read {{}} -> {{:?}}\", {:?}, {ident});",
                escape_rust_str(table)
            )
            .unwrap();
        }
        Action::Module { name, actions } => {
            writeln!(out, "{pad}{{ // module {name}").unwrap();
            for a in actions {
                emit_action(out, a, indent + 1);
            }
            writeln!(out, "{pad}}}").unwrap();
        }
        Action::Branch {
            condition,
            then_body,
            else_body,
        } => {
            let cond = emit_value_expr(condition);
            writeln!(out, "{pad}if {cond} {{").unwrap();
            for a in then_body {
                emit_action(out, a, indent + 1);
            }
            if else_body.is_empty() {
                writeln!(out, "{pad}}}").unwrap();
            } else {
                writeln!(out, "{pad}}} else {{").unwrap();
                for a in else_body {
                    emit_action(out, a, indent + 1);
                }
                writeln!(out, "{pad}}}").unwrap();
            }
        }
    }
}

fn infer_rhs(value: &ValueExpr) -> String {
    match value {
        ValueExpr::Bool(b) => b.to_string(),
        ValueExpr::I64(n) => n.to_string(),
        ValueExpr::F64(n) => format!("{n}"),
        ValueExpr::Str(s) => format!("{s:?}"),
        ValueExpr::Ident(name) => sanitize_ident(name),
        other => emit_value_expr(other),
    }
}

fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
