//! Core layer → Rust source (`main.rs`, `Cargo.toml`).

mod actions;
mod decls;

use ir::Program;
use std::fmt::Write;

use actions::emit_action;
use decls::{emit_enum, emit_function, emit_struct};

pub struct RustOutput {
    pub cargo_toml: String,
    pub main_rs: String,
}

pub fn emit(program: &Program) -> RustOutput {
    let mut main_rs = String::new();
    writeln!(
        &mut main_rs,
        "// Generated by Quantum Point — do not edit by hand.\n"
    )
    .unwrap();
    writeln!(
        &mut main_rs,
        "fn qp_mock_rows(table: &str) -> Vec<(&'static str, &'static str)> {{"
    )
    .unwrap();
    writeln!(&mut main_rs, "    match table {{").unwrap();
    writeln!(
        &mut main_rs,
        "        \"users\" => vec![(\"id\", \"1\"), (\"name\", \"Ada\")],"
    )
    .unwrap();
    writeln!(
        &mut main_rs,
        "        \"orders\" => vec![(\"id\", \"100\"), (\"total\", \"42\")],"
    )
    .unwrap();
    writeln!(
        &mut main_rs,
        "        _ => vec![(\"id\", \"0\"), (\"table\", table)],"
    )
    .unwrap();
    writeln!(&mut main_rs, "    }}").unwrap();
    writeln!(&mut main_rs, "}}\n").unwrap();

    for s in &program.structs {
        emit_struct(&mut main_rs, s);
    }
    for e in &program.enums {
        emit_enum(&mut main_rs, e);
    }
    for f in &program.functions {
        emit_function(&mut main_rs, f);
    }

    if program.needs_async_runtime {
        writeln!(&mut main_rs, "#[tokio::main]").unwrap();
        writeln!(&mut main_rs, "async fn main() {{").unwrap();
    } else {
        writeln!(&mut main_rs, "fn main() {{").unwrap();
    }
    for action in &program.actions {
        emit_action(&mut main_rs, action, 1);
    }
    writeln!(&mut main_rs, "}}").unwrap();

    let mut cargo_toml = r#"[workspace]

[package]
name = "qp_app"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "qp_app"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
"#
    .to_string();

    if program.needs_async_runtime {
        cargo_toml.push_str(
            r#"
[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
"#,
        );
    }

    RustOutput {
        cargo_toml,
        main_rs,
    }
}
